#正式服务器浏览图片(提供给前端IP)
fastDfs_ip: http://192.168.2.132:8090/
#测试服务器fastDFS 配置文件地址(上传测试服务器配置) 记得改tracker_server=192.168.2.132:22122
fastDfs_path: c:/fastDFS.properties

spring:
  profiles: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.179:3306/genealogy?characterEncoding=utf-8
    username: root
    password: 875Yhtpw758@
mybatis-plus:
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
  global-config:
    id-type: 0
  mapper-locations: classpath*:/mapper/**Mapper.xml
  typeAliasesPackage: com.genogram.entity
  configuration:
    #打印sql语句,调试用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


